sonar.projectKey=Benjamin-Yuji-Suzuki_logicfuzzy-academic
sonar.organization=benjamin-yuji-suzuki
sonar.language=rust
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.rust.clippy.disable=true
sonar.rust.lcov.reportPaths=lcov.info
