//! # variable.rs
//!
//! Linguistic fuzzy variables: universe of discourse, terms and variables.
//! Equivalent to `ctrl.Antecedent` / `ctrl.Consequent` from scikit-fuzzy.

use crate::membership::MembershipFn;

// ─────────────────────────────────────────────────────────────────
// Universe
// ─────────────────────────────────────────────────────────────────

/// Universe of discourse for a fuzzy variable.
///
/// Defines the numeric range [min, max] and the number of discretization points (resolution).
/// The discrete points are cached internally for performance.
///
/// Equivalent to the numpy array generated by `np.linspace(min, max, resolution)` in scikit-fuzzy.
#[derive(Debug, Clone)]
pub struct Universe {
    /// Minimum value of the universe (inclusive).
    pub min: f64,
    /// Maximum value of the universe (inclusive).
    pub max: f64,
    /// Number of discretization points (>= 2).
    pub resolution: usize,
    /// Cached discrete points of the universe.
    points_cache: Vec<f64>,
}

impl Universe {
    /// Creates a new universe. Requires `min < max`, `resolution >= 2`,
    /// and both `min` and `max` must be finite (no NaN or infinity).
    ///
    /// # Panics
    ///
    /// Panics if `min` or `max` is NaN, infinite, or if `min >= max` or `resolution < 2`.
    pub fn new(min: f64, max: f64, resolution: usize) -> Self {
        assert!(
            min.is_finite(),
            "Universe: min must be finite (not NaN or infinite)"
        );
        assert!(
            max.is_finite(),
            "Universe: max must be finite (not NaN or infinite)"
        );
        assert!(min < max, "Universe: min must be less than max");
        assert!(resolution >= 2, "Universe: resolution must be >= 2");
        let points_cache = (0..resolution)
            .map(|i| min + (max - min) * (i as f64) / ((resolution - 1) as f64))
            .collect();
        Self {
            min,
            max,
            resolution,
            points_cache,
        }
    }

    /// Alias for [`new`](Self::new) with a more readable argument order.
    pub fn with_resolution(min: f64, max: f64, n: usize) -> Self {
        Self::new(min, max, n)
    }

    /// Returns a reference to the cached vector of discrete points representing the universe.
    /// Equivalent to `np.linspace(min, max, resolution)`.
    pub fn points(&self) -> &[f64] {
        &self.points_cache
    }

    /// Step size between consecutive points.
    pub fn step(&self) -> f64 {
        (self.max - self.min) / ((self.resolution - 1) as f64)
    }
}

// ─────────────────────────────────────────────────────────────────
// Term
// ─────────────────────────────────────────────────────────────────

/// Linguistic term of a fuzzy variable.
#[derive(Debug, Clone)]
pub struct Term {
    pub label: String,
    pub mf: MembershipFn,
}

impl Term {
    pub fn new(label: impl Into<String>, mf: MembershipFn) -> Self {
        Self {
            label: label.into(),
            mf,
        }
    }

    pub fn eval(&self, x: f64) -> f64 {
        self.mf.eval(x)
    }

    pub fn eval_universe(&self, points: &[f64]) -> Vec<f64> {
        self.mf.eval_universe(points)
    }
}

// ─────────────────────────────────────────────────────────────────
// FuzzyVariable
// ─────────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct FuzzyVariable {
    pub name: String,
    pub universe: Universe,
    terms: Vec<Term>,
}

impl FuzzyVariable {
    pub fn new(name: impl Into<String>, universe: Universe) -> Self {
        Self {
            name: name.into(),
            universe,
            terms: Vec::new(),
        }
    }

    pub fn add_term(&mut self, term: Term) {
        assert!(
            !self.terms.iter().any(|t| t.label == term.label),
            "FuzzyVariable '{}': term '{}' already exists",
            self.name,
            term.label
        );
        self.terms.push(term);
    }

    pub fn get_term(&self, label: &str) -> Option<&Term> {
        self.terms.iter().find(|t| t.label == label)
    }

    pub fn membership_at(&self, label: &str, x: f64) -> f64 {
        match self.get_term(label) {
            Some(term) => term.eval(x),
            None => panic!(
                "FuzzyVariable '{}': term '{}' not found. Available terms: [{}]",
                self.name,
                label,
                self.term_labels().join(", ")
            ),
        }
    }

    pub fn fuzzify(&self, x: f64) -> Vec<(&str, f64)> {
        self.terms
            .iter()
            .map(|t| (t.label.as_str(), t.eval(x)))
            .collect()
    }

    pub fn term_labels(&self) -> Vec<&str> {
        self.terms.iter().map(|t| t.label.as_str()).collect()
    }

    pub fn term_count(&self) -> usize {
        self.terms.len()
    }

    pub fn terms(&self) -> &[Term] {
        &self.terms
    }

    /// Shortcut for `self.universe.points()`.
    pub fn universe_points(&self) -> &[f64] {
        self.universe.points()
    }

    pub fn term_membership_curve(&self, label: &str) -> Vec<f64> {
        let term = self
            .get_term(label)
            .unwrap_or_else(|| panic!("FuzzyVariable '{}': term '{}' not found", self.name, label));
        let pts = self.universe_points();
        term.eval_universe(pts)
    }

    /// Generates an SVG string visualizing all membership functions of this variable.
    pub fn to_svg(&self) -> String {
        crate::svg::render_variable_svg(self, None)
    }

    /// Generates an SVG with a vertical marker at the current input `value`.
    pub fn to_svg_with_input(&self, value: f64) -> String {
        crate::svg::render_variable_svg(self, Some(value))
    }
}

// ─────────────────────────────────────────────────────────────────
// Aliases
// ─────────────────────────────────────────────────────────────────

pub type AntecedentVar = FuzzyVariable;
pub type ConsequentVar = FuzzyVariable;

// ─────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::membership::MembershipFn;

    // ── Universe ───────────────────────────────────────────────

    #[test]
    fn universe_points_tamanho() {
        let u = Universe::new(0.0, 100.0, 1001);
        assert_eq!(u.points().len(), 1001);
    }

    #[test]
    fn universe_points_limites() {
        let u = Universe::new(0.0, 50.0, 501);
        let pts = u.points();
        assert_eq!(pts[0], 0.0);
        assert_eq!(pts[500], 50.0);
    }

    #[test]
    fn universe_points_meio() {
        let u = Universe::new(0.0, 100.0, 101);
        let pts = u.points();
        assert!((pts[50] - 50.0).abs() < 1e-10);
    }

    #[test]
    fn universe_step() {
        let u = Universe::new(0.0, 100.0, 101);
        assert!((u.step() - 1.0).abs() < 1e-10);
    }

    #[test]
    fn universe_dois_pontos() {
        let u = Universe::new(10.0, 20.0, 2);
        let pts = u.points();
        assert_eq!(pts.len(), 2);
        assert_eq!(pts[0], 10.0);
        assert_eq!(pts[1], 20.0);
    }

    #[test]
    #[should_panic(expected = "finite")]
    fn universe_rejects_nan_min() {
        Universe::new(f64::NAN, 10.0, 101);
    }

    #[test]
    #[should_panic(expected = "finite")]
    fn universe_rejects_nan_max() {
        Universe::new(0.0, f64::NAN, 101);
    }

    #[test]
    #[should_panic(expected = "finite")]
    fn universe_rejects_inf_min() {
        Universe::new(f64::INFINITY, 10.0, 101);
    }

    #[test]
    #[should_panic(expected = "finite")]
    fn universe_rejects_inf_max() {
        Universe::new(0.0, f64::NEG_INFINITY, 101);
    }

    #[test]
    #[should_panic(expected = "min must be less than max")]
    fn universe_rejects_min_eq_max() {
        Universe::new(5.0, 5.0, 101);
    }

    #[test]
    #[should_panic(expected = "resolution must be >= 2")]
    fn universe_rejects_resolution_1() {
        Universe::new(0.0, 10.0, 1);
    }

    // ── Term ───────────────────────────────────────────────────

    #[test]
    fn term_eval_pico() {
        let t = Term::new("alto", MembershipFn::Trimf([50.0, 100.0, 100.0]));
        assert_eq!(t.eval(100.0), 1.0);
    }
    #[test]
    fn term_eval_zero() {
        let t = Term::new("baixo", MembershipFn::Trimf([0.0, 0.0, 50.0]));
        assert_eq!(t.eval(100.0), 0.0);
    }
    #[test]
    fn term_label_preservado() {
        let t = Term::new("medio", MembershipFn::Trimf([0.0, 50.0, 100.0]));
        assert_eq!(t.label, "medio");
    }
    #[test]
    fn term_eval_universe_tamanho() {
        let t = Term::new("x", MembershipFn::Trimf([0.0, 50.0, 100.0]));
        let u = Universe::new(0.0, 100.0, 101);
        let graus = t.eval_universe(u.points());
        assert_eq!(graus.len(), 101);
    }

    // ── FuzzyVariable ──────────────────────────────────────────

    fn make_var() -> FuzzyVariable {
        let mut v = FuzzyVariable::new("temperatura", Universe::new(0.0, 50.0, 501));
        v.add_term(Term::new("fria", MembershipFn::Trimf([0.0, 0.0, 25.0])));
        v.add_term(Term::new("morna", MembershipFn::Trimf([0.0, 25.0, 50.0])));
        v.add_term(Term::new("quente", MembershipFn::Trimf([25.0, 50.0, 50.0])));
        v
    }

    #[test]
    fn var_term_count() {
        assert_eq!(make_var().term_count(), 3);
    }
    #[test]
    fn var_get_term_existente() {
        let v = make_var();
        assert!(v.get_term("morna").is_some());
    }
    #[test]
    fn var_get_term_inexistente() {
        let v = make_var();
        assert!(v.get_term("gelada").is_none());
    }
    #[test]
    fn var_membership_at_pico() {
        let v = make_var();
        assert_eq!(v.membership_at("fria", 0.0), 1.0);
        assert_eq!(v.membership_at("quente", 50.0), 1.0);
    }
    #[test]
    fn var_membership_at_morna_pico() {
        let v = make_var();
        assert!((v.membership_at("morna", 25.0) - 1.0).abs() < 1e-10);
    }
    #[test]
    fn var_membership_at_sem_pertinencia() {
        let v = make_var();
        assert_eq!(v.membership_at("fria", 50.0), 0.0);
    }
    #[test]
    fn var_fuzzify_retorna_todos_termos() {
        let v = make_var();
        let resultado = v.fuzzify(25.0);
        assert_eq!(resultado.len(), 3);
    }
    #[test]
    fn var_fuzzify_graus_corretos() {
        let v = make_var();
        let resultado = v.fuzzify(25.0);
        let morna = resultado.iter().find(|(l, _)| *l == "morna").unwrap().1;
        assert!((morna - 1.0).abs() < 1e-10);
    }
    #[test]
    fn var_fuzzify_ponto_intermediario() {
        let v = make_var();
        let resultado = v.fuzzify(12.5);
        let fria = resultado.iter().find(|(l, _)| *l == "fria").unwrap().1;
        let morna = resultado.iter().find(|(l, _)| *l == "morna").unwrap().1;
        assert!((fria - 0.5).abs() < 1e-10);
        assert!((morna - 0.5).abs() < 1e-10);
    }
    #[test]
    fn var_term_labels() {
        let v = make_var();
        let labels = v.term_labels();
        assert_eq!(labels, vec!["fria", "morna", "quente"]);
    }
    #[test]
    fn var_universe_points_tamanho() {
        let v = make_var();
        assert_eq!(v.universe_points().len(), 501);
    }
    #[test]
    fn var_membership_curve_tamanho() {
        let v = make_var();
        let curve = v.term_membership_curve("morna");
        assert_eq!(curve.len(), 501);
    }
    #[test]
    fn var_membership_curve_pico_correto() {
        let v = make_var();
        let pts = v.universe_points();
        let curve = v.term_membership_curve("morna");
        let idx_pico = pts.iter().position(|&p| (p - 25.0).abs() < 1e-9).unwrap();
        assert!((curve[idx_pico] - 1.0).abs() < 1e-10);
    }
    #[test]
    #[should_panic(expected = "already exists")]
    fn var_add_term_duplicado_panics() {
        let mut v = FuzzyVariable::new("v", Universe::new(0.0, 10.0, 101));
        v.add_term(Term::new("baixo", MembershipFn::Trimf([0.0, 0.0, 5.0])));
        v.add_term(Term::new("baixo", MembershipFn::Trimf([0.0, 0.0, 5.0])));
    }
    #[test]
    #[should_panic(expected = "not found")]
    fn var_membership_at_label_invalido_panics() {
        let v = make_var();
        v.membership_at("inexistente", 10.0);
    }

    #[test]
    fn antecedent_var_e_fuzzy_variable() {
        let mut ant: AntecedentVar = FuzzyVariable::new("umidade", Universe::new(0.0, 100.0, 101));
        ant.add_term(Term::new(
            "baixa",
            MembershipFn::Trapmf([0.0, 0.0, 30.0, 50.0]),
        ));
        assert_eq!(ant.membership_at("baixa", 0.0), 1.0);
    }

    #[test]
    fn consequent_var_e_fuzzy_variable() {
        let mut con: ConsequentVar =
            FuzzyVariable::new("velocidade", Universe::new(0.0, 100.0, 101));
        con.add_term(Term::new(
            "rapida",
            MembershipFn::Trimf([60.0, 100.0, 100.0]),
        ));
        assert_eq!(con.membership_at("rapida", 100.0), 1.0);
    }

    #[test]
    fn var_trapmf_plano_central() {
        let mut v = FuzzyVariable::new("v", Universe::new(0.0, 100.0, 1001));
        v.add_term(Term::new(
            "medio",
            MembershipFn::Trapmf([20.0, 35.0, 65.0, 80.0]),
        ));
        assert_eq!(v.membership_at("medio", 50.0), 1.0);
    }

    #[test]
    fn var_trapmf_rampa_aberta_esquerda() {
        let mut v = FuzzyVariable::new("v", Universe::new(0.0, 100.0, 1001));
        v.add_term(Term::new(
            "baixo",
            MembershipFn::Trapmf([0.0, 0.0, 25.0, 50.0]),
        ));
        assert_eq!(v.membership_at("baixo", 0.0), 1.0);
        assert_eq!(v.membership_at("baixo", 50.0), 0.0);
    }

    #[test]
    fn to_svg_retorna_string_nao_vazia() {
        let v = make_var();
        let svg = v.to_svg();
        assert!(!svg.is_empty());
        assert!(svg.contains("<svg"));
    }

    #[test]
    fn universe_with_resolution_alias() {
        let u1 = Universe::new(0.0, 10.0, 101);
        let u2 = Universe::with_resolution(0.0, 10.0, 101);
        assert_eq!(u1.points(), u2.points());
    }
}
