//! # variable.rs
//!
//! Linguistic fuzzy variables: universe of discourse, terms and variables.
//! Equivalent to `ctrl.Antecedent` / `ctrl.Consequent` from scikit-fuzzy.
//!
//! Usage pipeline:
//!   1. Create a `Universe` with [min, max, resolution]
//!   2. Create `Term`s with `MembershipFn`
//!   3. Group everything into `FuzzyVariable`
//!   4. Use `Antecedent` / `Consequent` as semantic aliases

use crate::membership::MembershipFn;

// ─────────────────────────────────────────────────────────────────
// Universe
// ─────────────────────────────────────────────────────────────────

/// Universe of discourse for a fuzzy variable.
///
/// Defines the numeric range [min, max] and the number of discretization points (resolution).
/// discretizacao (resolution). Quanto maior o resolution, mais precisa
/// a defuzzificacao por centroide — mas mais custoso computacionalmente.
///
/// Equivalent to the numpy array generated by `np.linspace(min, max, resolution)` in scikit-fuzzy.
/// ou np.linspace(min, max, resolution) do scikit-fuzzy.
///
/// # Exemplo
/// ```
/// use fuzzy_mamdani::Universe;
/// let u = Universe::new(0.0, 100.0, 1001);
/// let pts = u.points();
/// assert_eq!(pts.len(), 1001);
/// assert_eq!(pts[0], 0.0);
/// assert_eq!(pts[1000], 100.0);
/// ```
#[derive(Debug, Clone)]
pub struct Universe {
    /// Minimum value of the universe (inclusive).
    pub min: f64,
    /// Maximum value of the universe (inclusive).
    pub max: f64,
    /// Number of discretization points (>= 2).
    pub resolution: usize,
}

impl Universe {
    /// Creates a new universe. Requires `min < max` and `resolution >= 2`.
    pub fn new(min: f64, max: f64, resolution: usize) -> Self {
        assert!(min < max, "Universe: min must be less than max");
        assert!(resolution >= 2, "Universe: resolution must be >= 2");
        Self {
            min,
            max,
            resolution,
        }
    }

    /// Returns the vector of discrete points representing the universe.
    /// Equivalent to `np.linspace(min, max, resolution)`.
    ///
    /// # Exemplo
    /// ```
    /// use fuzzy_mamdani::Universe;
    /// let u = Universe::new(0.0, 10.0, 11);
    /// let pts = u.points();
    /// assert_eq!(pts.len(), 11);
    /// assert!((pts[5] - 5.0).abs() < 1e-10);
    /// ```
    pub fn points(&self) -> Vec<f64> {
        let n = self.resolution;
        (0..n)
            .map(|i| self.min + (self.max - self.min) * (i as f64) / ((n - 1) as f64))
            .collect()
    }

    /// Step size between consecutive points.
    pub fn step(&self) -> f64 {
        (self.max - self.min) / ((self.resolution - 1) as f64)
    }
}

// ─────────────────────────────────────────────────────────────────
// Term
// ─────────────────────────────────────────────────────────────────

/// Linguistic term of a fuzzy variable.
///
/// A `Term` associates a natural-language label ("low", "medium", "high")
/// with a membership function (`MembershipFn`).
///
/// Equivalent to the scikit-fuzzy assignment:
///   `variable['low'] = fuzz.trimf(variable.universe, [0, 0, 50])`
///
/// # Exemplo
/// ```
/// use fuzzy_mamdani::{Term, MembershipFn};
/// let t = Term::new("baixo", MembershipFn::Trimf([0.0, 0.0, 50.0]));
/// assert_eq!(t.label, "baixo");
/// assert_eq!(t.mf.eval(0.0), 1.0);
/// assert_eq!(t.mf.eval(50.0), 0.0);
/// ```
#[derive(Debug, Clone)]
pub struct Term {
    /// Linguistic label of the term (e.g., "low", "medium", "high").
    pub label: String,
    /// Membership function associated with this term.
    pub mf: MembershipFn,
}

impl Term {
    /// Creates a new term with a label and membership function.
    pub fn new(label: impl Into<String>, mf: MembershipFn) -> Self {
        Self {
            label: label.into(),
            mf,
        }
    }

    /// Evaluates the membership degree of value `x` for this term.
    pub fn eval(&self, x: f64) -> f64 {
        self.mf.eval(x)
    }

    /// Evaluates the membership degree for a full slice of universe points.
    pub fn eval_universe(&self, points: &[f64]) -> Vec<f64> {
        self.mf.eval_universe(points)
    }
}

// ─────────────────────────────────────────────────────────────────
// FuzzyVariable
// ─────────────────────────────────────────────────────────────────

/// Fuzzy linguistic variable with a universe of discourse and a collection of terms.
///
/// Combined equivalent of `ctrl.Antecedent` and `ctrl.Consequent` from scikit-fuzzy.
/// `Antecedent` and `Consequent` are semantic type aliases over this struct.
///
/// # Exemplo basico
/// ```
/// use fuzzy_mamdani::{FuzzyVariable, Universe, Term, MembershipFn};
///
/// let mut temp = FuzzyVariable::new("temperatura", Universe::new(0.0, 50.0, 501));
/// temp.add_term(Term::new("fria",   MembershipFn::Trimf([0.0,  0.0, 25.0])));
/// temp.add_term(Term::new("morna",  MembershipFn::Trimf([0.0, 25.0, 50.0])));
/// temp.add_term(Term::new("quente", MembershipFn::Trimf([25.0,50.0, 50.0])));
///
/// assert!((temp.membership_at("morna", 25.0) - 1.0).abs() < 1e-10);
/// assert!(temp.membership_at("fria",  50.0) == 0.0);
/// ```
#[derive(Debug, Clone)]
pub struct FuzzyVariable {
    /// Variable name (e.g., "temperature", "humidity").
    pub name: String,
    /// Universe of discourse for this variable.
    pub universe: Universe,
    /// List of linguistic terms associated with this variable.
    terms: Vec<Term>,
}

impl FuzzyVariable {
    /// Creates an empty fuzzy variable (no terms).
    pub fn new(name: impl Into<String>, universe: Universe) -> Self {
        Self {
            name: name.into(),
            universe,
            terms: Vec::new(),
        }
    }

    /// Adds a linguistic term to the variable.
    /// Panics if a term with the same label already exists.
    pub fn add_term(&mut self, term: Term) {
        assert!(
            !self.terms.iter().any(|t| t.label == term.label),
            "FuzzyVariable '{}': term '{}' already exists",
            self.name,
            term.label
        );
        self.terms.push(term);
    }

    /// Returns a reference to the term by label. Returns `None` if not found.
    pub fn get_term(&self, label: &str) -> Option<&Term> {
        self.terms.iter().find(|t| t.label == label)
    }

    /// Evaluates the membership degree of value `x` for the term `label`.
    /// Panics if the label does not exist in the variable.
    ///
    /// # Exemplo
    /// ```
    /// use fuzzy_mamdani::{FuzzyVariable, Universe, Term, MembershipFn};
    /// let mut v = FuzzyVariable::new("v", Universe::new(0.0, 10.0, 101));
    /// v.add_term(Term::new("alto", MembershipFn::Trimf([5.0, 10.0, 10.0])));
    /// assert_eq!(v.membership_at("alto", 10.0), 1.0);
    /// ```
    pub fn membership_at(&self, label: &str, x: f64) -> f64 {
        match self.get_term(label) {
            Some(term) => term.eval(x),
            None => panic!(
                "FuzzyVariable '{}': term '{}' not found. Available terms: [{}]",
                self.name,
                label,
                self.term_labels().join(", ")
            ),
        }
    }

    /// Returns the membership degrees of `x` across ALL terms.
    /// Returns a `Vec` of (label, degree) in the order terms were added.
    ///
    /// Useful in the fuzzification step: iterates all terms at once.
    pub fn fuzzify(&self, x: f64) -> Vec<(&str, f64)> {
        self.terms
            .iter()
            .map(|t| (t.label.as_str(), t.eval(x)))
            .collect()
    }

    /// Returns the labels of all terms in this variable.
    pub fn term_labels(&self) -> Vec<&str> {
        self.terms.iter().map(|t| t.label.as_str()).collect()
    }

    /// Returns the number of terms.
    pub fn term_count(&self) -> usize {
        self.terms.len()
    }

    /// Returns a reference to the internal slice of terms.
    pub fn terms(&self) -> &[Term] {
        &self.terms
    }

    /// Returns the discretized points of this variable's universe.
    /// Shortcut for `self.universe.points()`.
    pub fn universe_points(&self) -> Vec<f64> {
        self.universe.points()
    }

    /// Evaluates the MF of a term over the entire discretized universe.
    /// Returns a `Vec<f64>` with one degree per universe point.
    ///
    /// Equivalent to: `skfuzzy.trimf(var.universe, params)`
    pub fn term_membership_curve(&self, label: &str) -> Vec<f64> {
        let term = self
            .get_term(label)
            .unwrap_or_else(|| panic!("FuzzyVariable '{}': term '{}' not found", self.name, label));
        let pts = self.universe_points();
        term.eval_universe(&pts)
    }

    /// Generates an SVG string visualizing all membership functions of this variable.
    ///
    /// The SVG is self-contained and can be saved as a `.svg` file or embedded in HTML.
    /// No external dependencies required.
    ///
    /// # Example
    /// ```
    /// use fuzzy_mamdani::{fuzzy_var};
    /// let var = fuzzy_var!("temperature", 0.0, 50.0, 501,
    ///     "cold" => trimf [0.0,  0.0, 25.0],
    ///     "warm" => trimf [0.0, 25.0, 50.0],
    ///     "hot"  => trimf [25.0,50.0, 50.0],
    /// );
    /// let svg = var.to_svg();
    /// assert!(svg.starts_with("<svg"));
    /// std::fs::write("temperature.svg", &svg).ok();
    /// ```
    pub fn to_svg(&self) -> String {
        crate::svg::render_variable_svg(self, None)
    }

    /// Generates an SVG with a vertical marker at the current input `value`.
    ///
    /// Useful for visualizing how a specific crisp input is fuzzified.
    ///
    /// # Example
    /// ```
    /// use fuzzy_mamdani::{fuzzy_var};
    /// let var = fuzzy_var!("temperature", 0.0, 50.0, 501,
    ///     "cold" => trimf [0.0, 0.0, 25.0],
    ///     "hot"  => trimf [25.0,50.0,50.0],
    /// );
    /// let svg = var.to_svg_with_input(10.0);
    /// assert!(svg.contains("stroke-dasharray"));
    /// ```
    pub fn to_svg_with_input(&self, value: f64) -> String {
        crate::svg::render_variable_svg(self, Some(value))
    }
}

// ─────────────────────────────────────────────────────────────────
// Aliases semanticos: Antecedent e Consequent
// ─────────────────────────────────────────────────────────────────

/// Semantic alias for input variables (antecedents).
/// Equivalent to `ctrl.Antecedent` from scikit-fuzzy.
pub type Antecedent = FuzzyVariable;

/// Semantic alias for output variables (consequents).
/// Equivalent to `ctrl.Consequent` from scikit-fuzzy.
pub type Consequent = FuzzyVariable;

// ─────────────────────────────────────────────────────────────────
// Testes unitarios
// ─────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::membership::MembershipFn;

    // ── Universe ───────────────────────────────────────────────

    #[test]
    fn universe_points_tamanho() {
        let u = Universe::new(0.0, 100.0, 1001);
        assert_eq!(u.points().len(), 1001);
    }

    #[test]
    fn universe_points_limites() {
        let u = Universe::new(0.0, 50.0, 501);
        let pts = u.points();
        assert_eq!(pts[0], 0.0);
        assert_eq!(pts[500], 50.0);
    }

    #[test]
    fn universe_points_meio() {
        let u = Universe::new(0.0, 100.0, 101);
        let pts = u.points();
        assert!((pts[50] - 50.0).abs() < 1e-10);
    }

    #[test]
    fn universe_step() {
        let u = Universe::new(0.0, 100.0, 101);
        assert!((u.step() - 1.0).abs() < 1e-10);
    }

    #[test]
    fn universe_dois_pontos() {
        let u = Universe::new(10.0, 20.0, 2);
        let pts = u.points();
        assert_eq!(pts.len(), 2);
        assert_eq!(pts[0], 10.0);
        assert_eq!(pts[1], 20.0);
    }

    // ── Term ───────────────────────────────────────────────────

    #[test]
    fn term_eval_pico() {
        let t = Term::new("alto", MembershipFn::Trimf([50.0, 100.0, 100.0]));
        assert_eq!(t.eval(100.0), 1.0);
    }

    #[test]
    fn term_eval_zero() {
        let t = Term::new("baixo", MembershipFn::Trimf([0.0, 0.0, 50.0]));
        assert_eq!(t.eval(100.0), 0.0);
    }

    #[test]
    fn term_label_preservado() {
        let t = Term::new("medio", MembershipFn::Trimf([0.0, 50.0, 100.0]));
        assert_eq!(t.label, "medio");
    }

    #[test]
    fn term_eval_universe_tamanho() {
        let t = Term::new("x", MembershipFn::Trimf([0.0, 50.0, 100.0]));
        let u = Universe::new(0.0, 100.0, 101);
        let graus = t.eval_universe(&u.points());
        assert_eq!(graus.len(), 101);
    }

    // ── FuzzyVariable ──────────────────────────────────────────

    fn make_var() -> FuzzyVariable {
        let mut v = FuzzyVariable::new("temperatura", Universe::new(0.0, 50.0, 501));
        v.add_term(Term::new("fria", MembershipFn::Trimf([0.0, 0.0, 25.0])));
        v.add_term(Term::new("morna", MembershipFn::Trimf([0.0, 25.0, 50.0])));
        v.add_term(Term::new("quente", MembershipFn::Trimf([25.0, 50.0, 50.0])));
        v
    }

    #[test]
    fn var_term_count() {
        assert_eq!(make_var().term_count(), 3);
    }

    #[test]
    fn var_get_term_existente() {
        let v = make_var();
        assert!(v.get_term("morna").is_some());
        assert_eq!(v.get_term("morna").unwrap().label, "morna");
    }

    #[test]
    fn var_get_term_inexistente() {
        let v = make_var();
        assert!(v.get_term("gelada").is_none());
    }

    #[test]
    fn var_membership_at_pico() {
        let v = make_var();
        assert_eq!(v.membership_at("fria", 0.0), 1.0);
        assert_eq!(v.membership_at("quente", 50.0), 1.0);
    }

    #[test]
    fn var_membership_at_morna_pico() {
        let v = make_var();
        assert!((v.membership_at("morna", 25.0) - 1.0).abs() < 1e-10);
    }

    #[test]
    fn var_membership_at_sem_pertinencia() {
        let v = make_var();
        assert_eq!(v.membership_at("fria", 50.0), 0.0);
    }

    #[test]
    fn var_fuzzify_retorna_todos_termos() {
        let v = make_var();
        let resultado = v.fuzzify(25.0);
        assert_eq!(resultado.len(), 3);
        let labels: Vec<&str> = resultado.iter().map(|(l, _)| *l).collect();
        assert!(labels.contains(&"fria"));
        assert!(labels.contains(&"morna"));
        assert!(labels.contains(&"quente"));
    }

    #[test]
    fn var_fuzzify_graus_corretos() {
        let v = make_var();
        // Em x=25: morna=1.0, fria=0.0 (borda), quente=0.0 (borda)
        let resultado = v.fuzzify(25.0);
        let morna = resultado.iter().find(|(l, _)| *l == "morna").unwrap().1;
        assert!((morna - 1.0).abs() < 1e-10);
    }

    #[test]
    fn var_fuzzify_ponto_intermediario() {
        let v = make_var();
        // Em x=12.5: fria=0.5, morna=0.5
        let resultado = v.fuzzify(12.5);
        let fria = resultado.iter().find(|(l, _)| *l == "fria").unwrap().1;
        let morna = resultado.iter().find(|(l, _)| *l == "morna").unwrap().1;
        assert!((fria - 0.5).abs() < 1e-10);
        assert!((morna - 0.5).abs() < 1e-10);
    }

    #[test]
    fn var_term_labels() {
        let v = make_var();
        let labels = v.term_labels();
        assert_eq!(labels, vec!["fria", "morna", "quente"]);
    }

    #[test]
    fn var_universe_points_tamanho() {
        let v = make_var();
        assert_eq!(v.universe_points().len(), 501);
    }

    #[test]
    fn var_membership_curve_tamanho() {
        let v = make_var();
        let curve = v.term_membership_curve("morna");
        assert_eq!(curve.len(), 501);
    }

    #[test]
    fn var_membership_curve_pico_correto() {
        let v = make_var();
        let pts = v.universe_points();
        let curve = v.term_membership_curve("morna");
        // Pico de "morna" esta em 25.0
        let idx_pico = pts.iter().position(|&p| (p - 25.0).abs() < 1e-9).unwrap();
        assert!((curve[idx_pico] - 1.0).abs() < 1e-10);
    }

    #[test]
    #[should_panic(expected = "already exists")]
    fn var_add_term_duplicado_panics() {
        let mut v = FuzzyVariable::new("v", Universe::new(0.0, 10.0, 101));
        v.add_term(Term::new("baixo", MembershipFn::Trimf([0.0, 0.0, 5.0])));
        v.add_term(Term::new("baixo", MembershipFn::Trimf([0.0, 0.0, 5.0]))); // deve panics
    }

    #[test]
    #[should_panic(expected = "not found")]
    fn var_membership_at_label_invalido_panics() {
        let v = make_var();
        v.membership_at("inexistente", 10.0); // deve panics
    }

    // ── Aliases semanticos ─────────────────────────────────────

    #[test]
    fn antecedent_e_fuzzy_variable() {
        // Antecedent e so um alias — deve compilar e funcionar igual
        let mut ant: Antecedent = FuzzyVariable::new("umidade", Universe::new(0.0, 100.0, 101));
        ant.add_term(Term::new(
            "baixa",
            MembershipFn::Trapmf([0.0, 0.0, 30.0, 50.0]),
        ));
        assert_eq!(ant.membership_at("baixa", 0.0), 1.0);
    }

    #[test]
    fn consequent_e_fuzzy_variable() {
        let mut con: Consequent = FuzzyVariable::new("velocidade", Universe::new(0.0, 100.0, 101));
        con.add_term(Term::new(
            "rapida",
            MembershipFn::Trimf([60.0, 100.0, 100.0]),
        ));
        assert_eq!(con.membership_at("rapida", 100.0), 1.0);
    }

    // ── Integracao com trapmf ──────────────────────────────────

    #[test]
    fn var_trapmf_plano_central() {
        let mut v = FuzzyVariable::new("v", Universe::new(0.0, 100.0, 1001));
        v.add_term(Term::new(
            "medio",
            MembershipFn::Trapmf([20.0, 35.0, 65.0, 80.0]),
        ));
        // Qualquer ponto entre 35 e 65 deve retornar 1.0
        assert_eq!(v.membership_at("medio", 50.0), 1.0);
        assert_eq!(v.membership_at("medio", 35.0), 1.0);
        assert_eq!(v.membership_at("medio", 65.0), 1.0);
    }

    #[test]
    fn var_trapmf_rampa_aberta_esquerda() {
        let mut v = FuzzyVariable::new("v", Universe::new(0.0, 100.0, 1001));
        v.add_term(Term::new(
            "baixo",
            MembershipFn::Trapmf([0.0, 0.0, 25.0, 50.0]),
        ));
        assert_eq!(v.membership_at("baixo", 0.0), 1.0);
        assert_eq!(v.membership_at("baixo", 10.0), 1.0);
        assert_eq!(v.membership_at("baixo", 50.0), 0.0);
    }
}
